openapi: 3.0.0
info:
  version: '1'
  title: Order Management System
  description: Order management system with Ballerina
paths:
  /customer:
    post:
      operationId: "createCustomer"
      responses:
        '200':
          description: OK
        '500':
          description: Internal Error
  /customer/{customerId}:
    get:
      operationId: "getCustomerById"
      summary: Returns a customer by ID.
      parameters:
        - name: customerId
          in: path
          required: true
          description: The ID of the customer.
          schema:
            type: string
      responses:
        '200':
          description: A user object.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
servers:
  - url: http://api.example.com/v1
    description: Main product server