[project]
org-name= "dhanushka"
version= "0.1.0"

[build-options]
observability-included=true

[platform]
target = "java8"

[[platform.libraries]]
artafactId = "mysql-connector-java"
version = "8.0.19"
path = "/Users/dhanushka/Desktop/mysql-connector-java-8.0.19.jar"
groupId = "mysql"
modules = ["order_api", "order_command_handler"]
