[project]
org-name= "dhanushka"
version= "0.1.4"
license = ["Apache-2.0"]
authors = ["Dhanushka Madushan"]
keywords = ["ballerina", "order", "invoice"]
repository = "https://github.com/madushadhanushka/invoice_util"

[dependencies]
