[docker]
  [docker.dockerConfig]
    enable = false
    #name = ""
    #registry = ''
    #tag = ''
    #buildImage = ''
    #dockerHost = ''
    #dockerCertPath = ''
    #baseImage = ''
    #enableDebug = ''
    #debugPort = ''
    #push = ''
    #username = ''
    #password = ''
    #cmd = 'CMD gateway ${APP}'
  [docker.dockerCopyFiles]
    enable = false
    [[docker.dockerCopyFiles.files]]
        source = ''
        target = ''
        isBallerinaConf = false
[kubernetes]
  [kubernetes.kubernetesDeployment]
    enable = false
    #name = ''
    #labels = '{"": ""}'
    #replicas = ''
    #enableLiveness = ''
    #initialDelaySeconds = ''
    #periodSeconds = ''
    #livenessPort = ''
    #imagePullPolicy = ''
    #imagePullSecrets = ['']
    #image = ''
    #env = ''
    #buildImage = ''
    #cmd = 'CMD gateway ${APP} --b7a.config.file=conf/micro-gw.conf'
    [kubernetes.kubernetesDeployment.copyFiles]
        enable = false
        [[kubernetes.kubernetesDeployment.copyFiles.files]]
            source = ''
            target = ''
    [kubernetes.kubernetesDeployment.livenessProbe]
        enable = false
        port = ''
        initialDelaySeconds = ''
        periodSeconds = ''
    [kubernetes.kubernetesDeployment.readinessProbe]
        enable = false
        port = ''
        initialDelaySeconds = ''
        periodSeconds = ''
    #dockerHost = ''
    #dockerCertPath = ''
    #push = ''
    #registry = 'index.docker.io/${DOCKER_USERNAME}'
    #username = ''
    #password = ''
    #baseImage = ''
    #singleYAML = ''
  [kubernetes.kubernetesService]
    enable = false
    #name = ''
    #labels = '{"": ""}'
    #serviceType = ''
    #port = ''
  #[kubernetes.kubernetesServiceHttps]
      #enable = false
      #name = ''
      #labels = '{"": ""}'
      #serviceType = ''
      #port = ''
  #[kubernetes.kubernetesServiceHttp]
      #enable = false
      #name = ''
      #labels = '{"": ""}'
      #serviceType = ''
      #port = ''
  #[kubernetes.kubernetesServiceToken]
      #enable = false
      #name = ''
      #labels = '{"": ""}'
      #serviceType = ''
      #port = ''
  [kubernetes.kubernetesIngress]
    enable = false
    #name = ''
    #labels = '{"", ""}'
    #hostname = ''
    #annotations = ''
    #path = ''
    #targetPath = ''
    #ingressClass = ''
  [kubernetes.secureKubernetesIngress]
    enable = false
    #name = ''
    #labels = '{"": ""}'
    #hostname = ''
    #annotations = ''
    #path = ''
    #targetPath = ''
    #ingressClass = ''
    #keyStorePath = '${ballerina.home}/bre/security/ballerinaKeystore.p12'
    #keyStorePassword = '$env{Keystore_Password}'
  [kubernetes.kubernetesHpa]
    enable = false
    #name = ''
    #labels = '{"": ""}'
    #minReplicas = ''
    #maxReplicas = ''
    #cpuPrecentage = ''
  [kubernetes.kubernetesSecret]
    enable = false
    #[[kubernetes.kubernetesSecret.secrets]]
      #name = ''
      #mountPath = ''
      #readOnly = false
      #data = ['']
  [kubernetes.kubernetesConfigMap]
    enable = false
    ballerinaConf = 'path/to/micro-gw.conf'
    #[[kubernetes.kubernetesConfigMap.configMaps]]
      #name = ''
      #mountPath = ''
      #data = ['']
      #readOnly = false
  [kubernetes.kubernetesPersistentVolumeClaim]
    enable = false
    #name = ''
    #mountPath = ''
    #readOnly = ''
    #accessMode = ''
    #volumeClaimSize = ''
  [kubernetes.kubernetesJob]
    enable = false
    #name = ''
    #labels = '{"": ""}'
    #restartPolicy = ''
    #backoffLimit = ''
    #activeDeadlineSeconds = ''
    #schedule = ''
    #imagePullPolicy = ''
    #image = ''
    #env = ''
    #buildImage = ''
    #dockerHost = ''
    #dockerCertPath = ''
    #push = ''
    #username = ''
    #password = ''
    #baseImage = ''