[project]
org-name= "dhanushka"
version= "0.1.0"

[build-options]
observability-included=true

[b7a.observability.metrics]
enabled=true
reporter="prometheus"

[b7a.observability.metrics.prometheus]
port=9797
host="0.0.0.0"